### ISSUE TITLE
Writing a cookie, fetching another, failing on auth

### ISSUE THREAD

**Issue by arypbatista** [rojo2/passport-cookie#4]
Hi there!

I was trying to make the lib work but I couldn't complete authentication. After reading the implementation and reviewing the cookies set I found out that the auth cookie created was not the one read by the strategy.

I solved this by configuring the `CookieStrategy` with the cookie name set.

It would be great to explain that this coudl happen, why and how to prevent it.

Also, it would be great to return an error like "Cookie not set" or something, at least for debugging purposes.

**Comment by TerrySlack** [comment]
@arypbatista would you happen to have some sample code?  I also tried naming the cookie and I get the error message Unauthorized.

**Comment by AzazelN28** [comment]
Hi

First of all, thanks for using passport-cookie and for giving this useful feedback. I've updated the README.md to show how to configure the cookieName (and other options like signed or passReqToCallback).

I'm considering adding the "Cookie not set" error but I don't have much time lately to develop this.
