### ISSUE TITLE
Why session:false ?

### ISSUE THREAD

**Issue by BlakeBrown** [rojo2/passport-cookie#5]
Hey thank you for making this!

I had a question about this comment: "Requests containing cookies do not require session support, so the session option can be set to false."

For users to be authenticated don't we still need to keep track of their sessions in memory? If I set session:false as per the documentation I get `Error: Failed to serialize user into session` unless I write a serialize function.

**Comment by AzazelN28** [comment]
Hi!

Well, `passport` already has the ability to keep user session data using the middleware `passport.session()` (this also saves a cookie and keeps all user state in memory, I recommend it if you don't want to deal with cookies).

The idea behind this passport strategy is that you can have a slim strategy that only handles authentication cookies and then connect it with other libraries or custom code to keep sessions in a DB or even to use stateless authentication methods like: [JWT](https://jwt.io/) or [Macaroons](https://github.com/go-macaroon/js-macaroon).

**Comment by BlakeBrown** [comment]
Thanks @AzazelN28, appreciate the speedy response!

Seems to me like you don't even need passport to implement an authentication system with cookies? Using `cookie-session` you can just assign a user object to the session (during login) and retrieve the cookie on every subsequent request. The data is secure since the cookie is signed. Then you don't need any other library, is there anything I'm missing here?

Passport.js and this library would only be used if you wanted to store some user data in memory and fetch the user data using say a session ID from the cookie right?

**Comment by AzazelN28** [comment]
Indeed, but only if you don't need to support any other authentication method. 

Passport.js is great if you need to make a service with multiple authentication methods (e.g OAuth2) like Google, Facebook, Twitter, etc and some custom methods (e.g Auth. Bearer, Cookies or other) but if you don't need that I would go with something simpler.

**Comment by BlakeBrown** [comment]
That's super helpful info. I think I'll just go with plain cookies then since it provides all I need.

Thanks @AzazelN28 !
